global:
  resolve_timeout: 10m

route:
  receiver: 'telegram-alerts'
  
  group_by: [ '...' ]
  group_interval: 5m
  group_wait: 5s

receivers:
- name: 'telegram-alerts'
  telegram_configs:
    # Telegram bot token
    - bot_token: <secret> 

    # ID of the chat where to send the messages.
      chat_id: <secret>
      
      api_url: 'https://api.telegram.org' 
      
      parse_mode: Markdown

      message: "*{{ .CommonAnnotations.title }}*\n{{ .CommonAnnotations.description }}"
