{
 "title": "App Trace",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Read/Write", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Read top",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "topk(15,read_bytes_total)", "legendFormat": "{{file_name}}" }
   ]
  },
  {
   "title": "Write top",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "topk(15,write_bytes_total)", "legendFormat": "{{file_name}}" }
   ]
  },
  {
   "title": "Read rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(irate(read_bytes_total[5m]))",
     "legendFormat": "read"
    }
   ]
  },
  {
   "title": "Write rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(irate(write_bytes_total[5m]))"
    }
   ]
  },
  { "title": "TCP Trace", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "IP Map",
   "type": "geomap",
   "gridPos": { "h": 13, "w": 18, "x": 0, "y": 20 },
   "targets": [
    { "expr": "geoip_total{}" }
   ]
  },
  {
   "title": "Connections Established",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 6, "x": 18, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(connections_established_total)",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  {
   "title": "Received",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "bytes_received_total", "legendFormat": "{{ip}}" }
   ]
  },
  {
   "title": "Sent",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "bytes_sent_total", "legendFormat": "{{ip}}" }
   ]
  },
  {
   "title": "Received rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(bytes_received_total[5m])",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  {
   "title": "Sent rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    { "expr": "irate(bytes_sent_total[5m])", "legendFormat": "{{ip}}" }
   ]
  },
  { "title": "System Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "cpu_usage" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 5, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * memory_usage/total_memory"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    { "expr": "memory_usage", "legendFormat": "Memory usage" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "cpu_usage", "legendFormat": "CPU usage" }
   ]
  },
  { "title": "Other", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "Amount of syscalls",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 69 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "topk(15,syscalls_total)", "legendFormat": "{{func_name}}" }
   ]
  }
 ]
}